baseURL = 'https://www.floc26.org'
languageCode = 'en-us'
title = 'FLoC 2026'
theme = 'hugo-universal-theme'

[markup.goldmark.renderer]
  unsafe = true

defaultContentLanguage = "en"

[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    weight     = 2

[[menu.main]]
    name       = "About FLoC"
    url        = "/about/"
    weight     = 1
    parent     = "menu.about"

[[menu.main]]
    name       = "Committees"
    url        = "/committees/"
    weight     = 2
    parent     = "menu.about"

[params]
    dropdown_mouse_over = true
    disabled_logo = false
    logo_text = "FLoC'26"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><a href="mailto:webmaster@floc26.org" data-animate-hover="pulse"><i class="fas fa-envelope"></i> webmaster@floc26.org</a>
      </p>
      """
